name: Continuous Integration Frontend

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2

      - name: Login Docker
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag matthmul/node:latest

      - name: Docker Push
        run: docker push matthmul/node:latest