name: Deploy container app to Azure Web App - the-shop-backend

on:
  workflow_run:
    workflows: [Continuous Integration Backend]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c50582e7317e427e88addeeae9cbe7c4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0dfc7109b536466abed6f02d82bd13c9 }}
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'the-shop-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa7d615dbaf6405a854aa919167711d0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c50582e7317e427e88addeeae9cbe7c4 }}/java_scala_sbt:latest'
