name: Deploy container app to Azure Web App - the-shop-backend

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.13.6]
        java: [temurin@11]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: Scala
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2

      - name: Setup Java (temurin@11)
        if: matrix.java == 'temurin@11'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build project
        run: sbt ++${{ matrix.scala }} dist

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Unzip output
        run: unzip -qq shop-1.0.zip -d shop-1.0
        working-directory: Scala/target/universal

      - name: Login Docker
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag matthmul/java_scala_sbt:${{ github.sha }}

      - name: Docker Push
        run: docker push matthmul/java_scala_sbt:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c50582e7317e427e88addeeae9cbe7c4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0dfc7109b536466abed6f02d82bd13c9 }}
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'the-shop-backend'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa7d615dbaf6405a854aa919167711d0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c50582e7317e427e88addeeae9cbe7c4 }}/java_scala_sbt:${{ github.sha }}'
