name: Deploy container app to Azure Web App - the-shop

on:
  workflow_run:
    workflows: [Continuous Integration Frontend]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6e4cc4391fc64464a0aeb0073351c267 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0644d32a62d9427e81c282cde6ec7252 }}
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'the-shop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_84aa59e76cb348e793ac200352cf6252 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6e4cc4391fc64464a0aeb0073351c267 }}/node:latest'
