name: Deploy container app to Azure Web App - the-shop

on:
  workflow_run:
    workflows: [Continuous Integration Frontend]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_65e0cdbeccf346b3b43a61ab086429bd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ab783b1a54ca4a0c8ce0a8d10d16906d }}
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'the-shop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3a1e4d8f41124aa3be338e5f813456a2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_65e0cdbeccf346b3b43a61ab086429bd }}/node:latest'
